name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build
        run: |
          npm install
          node --experimental-wasm-eh scripts/step2json.js DragonBurnerAssembly.step > public/DragonBurnerAssembly.json
          npm run build

      - name: Publish to GH Pages
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "chirpy@gmail.com"
          git fetch
          git checkout gh-pages
          git rm assets/* || true
          git rm icons/* || true
          git rm img/* || true
          git rm libs/* || true
          git rm step/* || true          
          cp -Rv dist/spa/* .
          git add -v index.html
          git add -v assets/
          git add -v icons/
          git add -v img/
          git add -v step/
          git add -v libs/
          git add favicon.ico
          git commit -m 'Built from ${{ github.ref }}'
          git push origin gh-pages
